version: '3.0'

volumes:
  esdata:
    name: esdata

services:
  es:
    container_name: es
    image: elasticsearch:7.10.1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "esdata:/usr/share/elasticsearch/data"
    environment:
      - discovery.type=single-node

  kibana:
    image: kibana:7.10.1
    ports:
      - "5601:5601"
    environment:
      - 'ELASTICSEARCH_HOSTS=["http://es:9200"]'